# Basic docker-compose.yml running the project as docker container.
# Configuration of needed parameters can be done via ./.env file.
# This file isn't loaded into the image, just used as a source for environment variables.

services:
  dalle-discord-bot:
    image: dalle-discord-bot:latest
    build: .
    container_name: dalle-discord-bot
    restart: unless-stopped
    env_file: .env
    environment:
      - SOURCES_PERSISTENCE_FILE=/persistence/all
    volumes:
      - ./persistence/:/persistence/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
networks:
  default:
    name: dalle-discord-bot-network
    driver: bridge

